In [2]:
import ccxt, yfinance
import pandas_ta as ta
import pandas as pd

In [19]:
exchange = ccxt.binance()

bars = exchange.fetch_ohlcv('BTC/USDT', timeframe='15m', limit=500000)

In [20]:
df = pd.DataFrame(bars, columns=['time', 'open', 'high', 'low', 'close', 'volume'])
df

              time      open      high       low     close     volume
0    1695210300000  27114.24  27117.20  27088.43  27098.08  130.37581
1    1695211200000  27098.07  27127.89  27098.07  27102.11  225.35461
2    1695212100000  27102.11  27130.00  27080.54  27090.00  384.10007
3    1695213000000  27089.99  27090.00  27010.07  27029.23  418.13860
4    1695213900000  27029.23  27080.42  26997.94  27068.28  266.32336
..             ...       ...       ...       ...       ...        ...
995  1696105800000  27029.70  27068.59  27029.70  27067.00   85.54681
996  1696106700000  27067.00  27073.11  27060.00  27064.15  116.39665
997  1696107600000  27064.15  27080.41  27064.14  27076.60  113.58631
998  1696108500000  27076.60  27081.78  27065.80  27065.80  100.28139
999  1696109400000  27065.80  27065.81  27049.77  27049.78   25.33638

[1000 rows x 6 columns]

In [ ]:
if __name__ == '__main__':
    pass